templateComponents:
    VW:
        activation, credit-note, voucher-invoice-de, voucher-invoice-eu:
            root: root-1
    SKODA:
        activation, credit-note:
            root: root-1

templateAttributes:
    VW:
        activation, credit-note, voucher-invoice-de, voucher-invoice-eu:
            root-1:
                root: font-family="Arial, sans-serif, SimSun"
                simple-page-master[master-name="first-page"]: page-height="29.7cm" page-width="21cm" margin-top="2.3cm" margin-bottom="2cm" margin-left="2cm" margin-right="2cm"
                simple-page-master[master-name="first-page"] region-body: margin-top="4cm" margin-bottom="3cm"
                simple-page-master[master-name="first-page"] region-before: extent="1cm"
                simple-page-master[master-name="first-page"] region-after: extent="3cm" margin-bottom="2cm"
                simple-page-master[master-name="all-pages"]: page-height="29.7cm" page-width="21cm" margin-top="2.3cm" margin-bottom="2cm" margin-left="2cm" margin-right="2cm"
                simple-page-master[master-name="all-pages"] region-body: margin-top="5.5cm" margin-bottom="3cm"
                simple-page-master[master-name="all-pages"] region-before: extent="1cm"
                simple-page-master[master-name="all-pages"] region-after: extent="3cm" margin-bottom="2cm"
    SKODA:
        activation, credit-note:
            root-1:
                root: font-family="SKODANext, sans-serif, SimSun"
                simple-page-master[master-name="first-page"]: page-height="29.7cm" page-width="21cm" margin-top="0.6cm" margin-bottom="2cm" margin-left="1.2cm" margin-right="1cm"
                simple-page-master[master-name="first-page"] region-body: margin-top="3.109cm" margin-bottom="3cm"
                simple-page-master[master-name="first-page"] region-before: extent="1cm"
                simple-page-master[master-name="first-page"] region-after: extent="3.5cm" margin-bottom="2cm"
                simple-page-master[master-name="all-pages"]: page-height="29.7cm" page-width="21cm" margin-top="0.6cm" margin-bottom="2cm" margin-left="1.2cm" margin-right="1cm"
                simple-page-master[master-name="all-pages"] region-body: margin-top="3.5cm" margin-bottom="3cm"
                simple-page-master[master-name="all-pages"] region-before: extent="1cm"
                simple-page-master[master-name="all-pages"] region-after: extent="3.5cm" margin-bottom="2cm"