templateLayout:
  VW:
    activation, credit-note, voucher-invoice-de, voucher-invoice-eu:
      root:
        attributes: font-family="Arial, sans-serif, SimSun"
        layout-master-set:
          simple-page-master:
            -
              master-name: first-page
              attributes: page-height="29.7cm" page-width="21cm" margin-top="2.3cm" margin-bottom="2cm" margin-left="2cm" margin-right="2cm"
              region-body:
                region-name: xsl-region-body
                attributes: margin-top="4cm" margin-bottom="3cm"
              region-before:
                region-name: xsl-region-before-first
                attributes: extent="1cm"
              region-after:
                region-name: xsl-region-after
                attributes: extent="3cm" margin-bottom="2cm"
            -
              master-name: all-pages
              attributes: page-height="29.7cm" page-width="21cm" margin-top="2.3cm" margin-bottom="2cm" margin-left="2cm" margin-right="2cm"
              region-body:
                region-name: xsl-region-body
                attributes: margin-top="5.5cm" margin-bottom="3cm"
              region-before:
                region-name: xsl-region-before
                attributes: extent="1cm"
              region-after:
                region-name: xsl-region-after
                attributes: extent="3cm" margin-bottom="2cm"
          page-sequence-master:
              master-name: my-sequence
              single-page-master-reference:
                master-reference: first-page
              repeatable-page-master-reference:
                master-reference: all-pages
        page-sequence:
          master-reference: my-sequence
          static-content:
            - flow-name: xsl-region-before-first
            - flow-name: xsl-region-before
            - flow-name: xsl-region-after

    voucher-delivery:
      root:
        attributes: font-family="Arial, sans-serif, SimSun"
        layout-master-set:
          simple-page-master:
            -
              master-name: my-sequence
              attributes: page-height="29.7cm" page-width="21cm"
        page-sequence:
          master-reference: my-sequence

  SKODA:
    activation, credit-note:
      root:
        attributes: font-family="SKODANext, sans-serif, SimSun"
        layout-master-set:
          simple-page-master:
            - master-name: first-page
              attributes: page-height="29.7cm" page-width="21cm" margin-top="0.6cm" margin-bottom="2cm" margin-left="1.2cm" margin-right="1cm"
              region-body:
                region-name: xsl-region-body
                attributes: margin-top="3.109cm" margin-bottom="3cm"
              region-before:
                region-name: xsl-region-before-first
                attributes: extent="1cm"
              region-after:
                region-name: xsl-region-after
                attributes: extent="3.5cm" margin-bottom="2cm"
            - master-name: all-pages
              attributes: page-height="29.7cm" page-width="21cm" margin-top="0.6cm" margin-bottom="2cm" margin-left="1.2cm" margin-right="1cm"
              region-body:
                region-name: xsl-region-body
                attributes: margin-top="3.5cm" margin-bottom="3cm"
              region-before:
                region-name: xsl-region-before
                attributes: extent="1cm"
              region-after:
                region-name: xsl-region-after
                attributes: extent="3.5cm" margin-bottom="2cm"
          page-sequence-master:
            master-name: my-sequence
            single-page-master-reference:
              master-reference: first-page
            repeatable-page-master-reference:
              master-reference: all-pages
        page-sequence:
          master-reference: my-sequence
          static-content:
            - flow-name: xsl-region-before-first
            - flow-name: xsl-region-before
            - flow-name: xsl-region-after


templateFlow:
  VW:
    activation, credit-note, voucher-invoice-de, voucher-invoice-eu:
      xsl-region-before-first:
      xsl-region-before:
      xsl-region-after:
      xsl-region-body:

    voucher-delivery:
      xsl-region-body:

  SKODA:
    activation, credit-note, voucher-invoice-de, voucher-invoice-eu:
      xsl-region-before-first:
      xsl-region-before:
      xsl-region-after:
      xsl-region-body: