templateContentKeys:
  field[customerInformation]:
    field[salutation]:
      value[MR]:
        salutation: customerSalutation-MR
      value[MRS]:
        salutation: customerSalutation-MRS
      value[MS]:
        salutation: customerSalutation-MS
      value[MS2]:
        salutation: customerSalutation-MS2

  field[brand]:
    value[VW]:
      field[mailTypeVariant]:
        value[credit-node]:
          headingtitle: label.credit.note

      commercialregister: invoice.text.commercialregister
      vatvw: invoice.text.vatvw
      postalvw: invoice.text.postalvw
      board: invoice.text.board
      headingtitle: invoice.subheadline.shop

    value[SKODA]:
      field[mailTypeVariant]:
        value[activation]:
          headingtitle: invoice.subheadline.shop
        value[credit-node]:
          headingtitle: invoice.label.credit-note

      footeraddress: invoice.footer.address

  pagenumbercitation: invoice.text.page


templateLayout:
  field[brand]:
    value[VW]:
      root: root-v1.1

      field[mailTypeVariant]:
        value[voucher-delivery]:
          root: root-v2

    value[SKODA]:
      root: root-v1.2

templateFlowComponents:
  block-container-external-graphic:
    external-graphic:
      src: classpath:{//logo}

  salutation-block:
    field[customerInformation]:
      field[customerType]:
        value[PRIVATE]:
          text-space-v1:
            - contentKey: templateContentKeys.salutation
            - requestField: //request/customerInformation/firstName
            - requestField: //request/customerInformation/lastName
        value[COMPANY]:
          requestField: //request/customerInformation/company

templateFlow:
  field[brand]:
    value[VW]:
      xsl-region-before-first:
        - templateFlowComponents.block-container-external-graphic
      xsl-region-before:
        - templateFlowComponents.block-container-external-graphic
        - page-number-citation:
            attributes: text-align="end" font-size="10pt" margin-top="12mm"
            contentKey: templateContentKeys.pagenumbercitation
      xsl-region-after:
        - block:
            attributes: font-size="7pt" color="#B4B8BA" margin-bottom="0.5cm"
            contentKey: templateContentKeys.vatvw
            text-block:
              contentKey: templateContentKeys.commercialregister
        - block:
            attributes: font-size="7pt"
            table-row-1:
              table-cell:
                - block:
                    attributes: color="#B4B8BA"
                    contentKey: templateContentKeys.postalvw
                - block:
                    attributes: color="#B4B8BA"
                - block:
                    attributes: color="#B4B8BA"
                    contentKey: templateContentKeys.board
      xsl-region-body:
        - table-row-1:
            table-cell:
              - block:
                  attributes: font-size="16pt" color="#899093" font-weight="bold"
                  contentKey: templateContentKeys.headingtitle
              - page-number-citation:
                  attributes: text-align="end" font-size="10pt"
                  contentKey: templateContentKeys.pagenumbercitation
                attributes: display-align="after"
        - block:
            table-row-1:
              attributes: font-size="10pt" space-before="15mm"
              table-column:
                - attributes: column-width="55%"
                - attributes: column-width="45%"
              table-cell:
                - block-container:
                    attributes: width="85%"
                    block: templateFlowComponents.salutation-block

      field[mailTypeVariant]:
        value[voucher-delivery]:


    value[SKODA]:
      xsl-region-before-first:
      xsl-region-before:
      xsl-region-after:
      xsl-region-body: